use_frameworks!

platform :ios, '8.0'

target 'ShareComponent_Example' do
  pod 'ShareComponent', :path => '../'

  target 'ShareComponent_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
